version: '3'

services:
  frontend:
    build: 
      context: ./ProjectFrontEnd
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./ProjectFrontEnd:/app

