version: '3'

services:
  frontend:
    image: styxql/frontend_twitter
    container_name: frontend
    restart: always
    ports:
      - 3200:5173

  laravel:
    image: styxql/api_twitter
    ports:
      - 5020:80
    depends_on:
      - db

  db:
    image: styxql/bd_twitter
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: twitterbdd  
      MYSQL_USER: mon_user  
      MYSQL_PASSWORD: mon_mot_de_passe  
    volumes:
      - "./db-lib:/var/lib/mysql"
    restart: always
  
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "1313:80"
    environment:
      PMA_HOST: db
      PMA_USER: mon_user  
      PMA_PASSWORD: mon_mot_de_passe  
      PMA_ARBITRARY: 1
    depends_on:
      - db
